.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. schleems_qt test_schleems_qt
clean: FORCE
	$(MAKE) -C .. schleems_qt_clean test_schleems_qt_clean
check: FORCE
	$(MAKE) -C .. test_schleems_qt_check
schleems-qt schleems-qt.exe: FORCE
	 $(MAKE) -C .. schleems_qt
